import { c as create_ssr_component, e as escape, d as add_attribute, v as validate_component } from "../../../../chunks/ssr.js";
import { A as Attr } from "../../../../chunks/Attr.js";
const ProductPreviewCard_svelte_svelte_type_style_lang = "";
const css = {
  code: `@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,700&family=Montserrat:wght@500;700&display=swap');:root{--ppc-color-dark-cyan:hsl(158, 36%, 37%);--ppc-color-darker-cyan:hsl(158, 38%, 20%);--ppc-color-cream:hsl(30, 38%, 92%);--ppc-color-very-dark-blue:: hsl(212, 21%, 14%);--ppc-color-dark-grayish-blue:hsl(228, 12%, 48%);--ppc-color-white:hsl(0, 0%, 100%)}section.svelte-1p64fri.svelte-1p64fri{font-size:14px;font-family:"Montserrat", sans-serif;background-color:var(--ppc-color-cream);display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:calc(100vh - 0.1px)}.product-card.svelte-1p64fri.svelte-1p64fri{max-width:600px;padding:15px}.product-image.svelte-1p64fri img.svelte-1p64fri{border-radius:1rem 1rem 0 0}.product-details.svelte-1p64fri.svelte-1p64fri{background-color:var(--ppc-color-white);padding:1.5rem;border-radius:0 0 1rem 1rem;margin-top:-1rem}img.svelte-1p64fri.svelte-1p64fri{max-width:100%}.category.svelte-1p64fri.svelte-1p64fri{text-transform:uppercase;font-size:0.8rem;font-weight:500;color:var(--ppc-color-dark-grayish-blue);margin-top:1rem;letter-spacing:0.3rem;margin-bottom:1.5rem}.title.svelte-1p64fri.svelte-1p64fri{color:var(--ppc-color-very-dark-blue);margin-bottom:1rem;font-size:2rem;line-height:1}.price.svelte-1p64fri.svelte-1p64fri{color:var(--ppc-color-dark-cyan)}.title.svelte-1p64fri.svelte-1p64fri,.price.svelte-1p64fri.svelte-1p64fri{font-family:"Fraunces", sans-serif}.description.svelte-1p64fri.svelte-1p64fri{color:var(--ppc-color-dark-grayish-blue);line-height:1.8;margin-bottom:1.5rem}ul.svelte-1p64fri.svelte-1p64fri{display:flex;align-items:center;margin-bottom:2rem;list-style-type:none}ul.svelte-1p64fri li.svelte-1p64fri:first-child{font-size:2rem;margin-right:1rem}ul.svelte-1p64fri li.svelte-1p64fri:nth-child(2){color:var(--ppc-color-dark-grayish-blue)}.btn.svelte-1p64fri.svelte-1p64fri{display:flex;align-items:center;justify-content:center;background-color:var(--ppc-color-dark-cyan);color:var(--ppc-color-white);font-weight:700;font-size:1rem;padding:1rem 2rem;width:100%;border:none;border-radius:0.625rem;outline:none;cursor:pointer;transition:0.3s}.btn.svelte-1p64fri.svelte-1p64fri:hover{background-color:var(--ppc-color-darker-cyan)}.btn.svelte-1p64fri img.svelte-1p64fri{margin-right:0.5rem}@media(min-width: 640px){.product-card.svelte-1p64fri.svelte-1p64fri{display:grid;grid-template-columns:repeat(2, 1fr);padding:0\r
    }.product-image.svelte-1p64fri img.svelte-1p64fri{border-radius:0.625rem 0 0 0.625rem;width:100%}.product-details.svelte-1p64fri.svelte-1p64fri{border-radius:0 0.625rem 0.625rem 0;margin-top:0;padding:1.5rem 2rem 1.5rem}picture.svelte-1p64fri img.svelte-1p64fri{height:100%}.description.svelte-1p64fri.svelte-1p64fri{margin-bottom:1rem}}`,
  map: null
};
const imageSrc = "https://ik.imagekit.io/ivw8jbdbt/FEMC/image-product-desktop";
const imageSrcM = "https://ik.imagekit.io/ivw8jbdbt/FEMC/image-product-mobile";
const iconCart = "https://ik.imagekit.io/ivw8jbdbt/FEMC/icon-cart.svg";
const ProductPreviewCard = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="container svelte-1p64fri" role="main"><div class="product-card svelte-1p64fri"><div class="product-image svelte-1p64fri"><picture class="svelte-1p64fri"><source media="(min-width: 640px)" srcset="${escape(imageSrc, true) + ".avif,\r\n                    " + escape(imageSrc, true) + ".jpg"}"> <source type="image/avif" srcset="${escape(imageSrcM, true) + ".avif"}"> <source type="image/webp" srcset="${escape(imageSrcM, true) + ".webp"}"> <source type="image/jpg" srcset="${escape(imageSrcM, true) + ".jpg"}"> <img src="${escape(imageSrcM, true) + ".png"}" alt="A product bottle of Chanel perfume" class="svelte-1p64fri"></picture></div> <div class="product-details svelte-1p64fri"><h3 class="category svelte-1p64fri" data-svelte-h="svelte-yw2b4j">Perfume</h3> <h1 class="title svelte-1p64fri" data-svelte-h="svelte-2nzkgt">Gabrielle Essence Eau De Parfum</h1> <p class="description svelte-1p64fri" data-svelte-h="svelte-4xg9s5">A floral, solar and voluptuous interpretation composed by Olivier Polge, Perfumer-Creator for the House of CHANEL.</p> <ul class="svelte-1p64fri" data-svelte-h="svelte-zwsq7j"><li class="price svelte-1p64fri">$149.99</li> <li class="svelte-1p64fri"><s>$169.99</s></li></ul> <button class="btn svelte-1p64fri"><img${add_attribute("src", iconCart, 0)} alt="Cart Icon" class="svelte-1p64fri"> Add to Cart</button></div></div> ${validate_component(Attr, "Attr").$$render($$result, {}, {}, {})} </section>`;
});
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `${validate_component(ProductPreviewCard, "ProductPreviewCard").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
