import { c as create_ssr_component, a as subscribe, e as escape, v as validate_component } from "../../../../chunks/ssr.js";
import { A as Attr } from "../../../../chunks/Attr.js";
import { g as glbVars } from "../../../../chunks/stores.js";
const ProfileCard_svelte_svelte_type_style_lang = "";
const css = {
  code: `@import url('https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap');:root{--pc-color-dark-cyan:hsl(185, 75%, 39%);--pc-color-very-dark-desaturated-blue:hsl(229, 23%, 23%);--pc-color-dark-grayish-blue:hsl(227, 10%, 46%);--pc-color-dark-gray:hsl(0, 0%, 59%);--pc-color-light-gray:hsla(0, 0%, 59%, 0.2)}.container.svelte-1od7at9.svelte-1od7at9{font-family:'Kumbh Sans',sans-serif;font-size:18px;height:100vh;position:relative;background:var(--pc-color-dark-cyan);color:var(--pc-color-very-dark-desaturated-blue);display:flex;align-items:center;justify-content:center;overflow:hidden}.top-bg.svelte-1od7at9.svelte-1od7at9{position:absolute;background:url("https://ik.imagekit.io/ivw8jbdbt/FEMC/bg-pattern-top.svg");background-size:contain;background-repeat:no-repeat;height:978px;width:978px;top:-528px;left:-284px}.bottom-bg.svelte-1od7at9.svelte-1od7at9{position:absolute;background:url("https://ik.imagekit.io/ivw8jbdbt/FEMC/bg-pattern-bottom.svg");background-size:contain;background-repeat:no-repeat;height:978px;width:978px;bottom:-600px;right:-220px}.card.svelte-1od7at9.svelte-1od7at9{background:white;font-size:18px;height:auto;width:350px;border-radius:20px;z-index:99;position:relative}.card.svelte-1od7at9 .cover-photo.svelte-1od7at9{height:142px;background:url("https://ik.imagekit.io/ivw8jbdbt/FEMC/bg-pattern-card.svg");border-radius:20px 20px 0 0;z-index:99}.profile.svelte-1od7at9 .pic.svelte-1od7at9{left:50%;transform:translateX(-50%);top:94px;background:white;position:absolute;padding:5px;border-radius:50%;display:flex;align-items:center;justify-content:center}.profile.svelte-1od7at9 .pic img.svelte-1od7at9{border-radius:50%}.profile-info.svelte-1od7at9.svelte-1od7at9{margin-top:74px;display:flex;align-items:center;flex-direction:column}.profile.svelte-1od7at9.svelte-1od7at9{width:100%;text-align:center;border-bottom:1px solid var(--pc-color-light-gray);padding-bottom:25px}.stats.svelte-1od7at9.svelte-1od7at9{padding:25px 0;text-align:center;width:100%;display:flex;align-items:center;justify-content:space-evenly;font-size:12px}.profile.svelte-1od7at9 .name.svelte-1od7at9{font-size:20px;margin-bottom:13px;color:var(--pc-color-dark-grayish-blue)}.profile.svelte-1od7at9 .name span.svelte-1od7at9{font-weight:700;padding:0 5px;color:var(--pc-color-very-dark-desaturated-blue)}.profile.svelte-1od7at9 .location.svelte-1od7at9{color:var(--pc-color-dark-grayish-blue);font-size:16px}.stats.svelte-1od7at9 p.svelte-1od7at9{color:var(--pc-color-dark-grayish-blue)}.stats.svelte-1od7at9 .number.svelte-1od7at9{font-size:20px;font-weight:700;margin-bottom:5px;color:var(--pc-color-very-dark-desaturated-blue)}.stats.svelte-1od7at9 .label.svelte-1od7at9{letter-spacing:2px}@media(max-width: 375px){.top-bg.svelte-1od7at9.svelte-1od7at9{height:375px;width:375px;top:-160px;left:-167px}.bottom-bg.svelte-1od7at9.svelte-1od7at9{height:375px;width:375px;bottom:-79px;right:-167px}}`,
  map: null
};
const ProfileCard = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $glbVars, $$unsubscribe_glbVars;
  $$unsubscribe_glbVars = subscribe(glbVars, (value) => $glbVars = value);
  $$result.css.add(css);
  $$unsubscribe_glbVars();
  return `<section class="container svelte-1od7at9" role="main"><div class="profile-card"><div class="top-bg svelte-1od7at9"></div> <div class="bottom-bg svelte-1od7at9"></div> <div class="card svelte-1od7at9"><div class="cover-photo svelte-1od7at9"></div> <div class="profile-info svelte-1od7at9"><div class="profile svelte-1od7at9"><div class="pic svelte-1od7at9"><img src="${escape($glbVars.cdnUrl, true) + "/image-victor.jpg"}" alt="Victor Crest" class="svelte-1od7at9"></div> <h1 class="name svelte-1od7at9" data-svelte-h="svelte-1n2a4ef"><span class="svelte-1od7at9">Victor Crest</span> 26</h1> <h2 class="location svelte-1od7at9" data-svelte-h="svelte-9uwup6">London</h2></div> <div class="stats svelte-1od7at9" data-svelte-h="svelte-12uk022"><div class="followers"><p class="number svelte-1od7at9">80K</p> <p class="label svelte-1od7at9">Followers</p></div> <div class="likes"><p class="number svelte-1od7at9">803K</p> <p class="label svelte-1od7at9">Likes</p></div> <div class="photos"><p class="number svelte-1od7at9">1.4K</p> <p class="label svelte-1od7at9">Photos</p></div></div></div></div></div> ${validate_component(Attr, "Attr").$$render($$result, {}, {}, {})} </section>`;
});
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `${validate_component(ProfileCard, "ProfileCard").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
